trigger:
<<<<<<< HEAD
  - master
  
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - script: echo K8S Terraform Azure!
    displayName: 'Run a one-line script'
  - task: DownloadSecureFile@1
    name: publickey
    inputs:
      secureFile: 'azure_rsa.pub'
  
  - task: TerraformTaskV2@2
    inputs:
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
      backendType: 'azurerm'
      backendServiceArm: 'azure-service-connection'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'backend-rg'
      backendAzureRmResourceGroupLocation: 'eastus'
      backendAzureRmStorageAccountName: 'storageacctnamexm1'
      backendAzureRmContainerName: 'storageaccntcon'
      backendAzureRmKey: 'k8.tfstate'
  - task: TerraformTaskV2@2
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
      environmentServiceName: 'azure-service-connection'
      commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
      environmentServiceNameAzureRM: 'Visual Studio Enterprise Subscription(a88a9629-4036-42fe-a0af-0587ea295017)'
=======
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformTaskV2@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    backendType: 'azurerm'
    backendServiceArm: 'azure-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmResourceGroupLocation: 'eastus'
    backendAzureRmStorageAccountName: 'storageacctnamexm1'
    backendAzureRmContainerName: 'storageaccntcon'
    backendAzureRmKey: 'k8.tfstate'
- task: TerraformTaskV2@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure'
    environmentServiceName: 'azure-service-connection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
>>>>>>> 7017e0e436d9962c931bd7db9663bc3711b09ee6
